//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeheadEmAll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeheadEmAll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------------------------------
        ///DeheadEmAll - Help version 20220308
        ///Copyright (c) 2016-2022 DeheadEmAll - All Rights Reserved
        ///---------------------------------------------------------------
        ///
        ///[I] About
        ///[II] Notes
        ///[III] Requirements
        ///[IV] Installation
        ///[V] How to Deheader ROMs
        ///[VI] Disclaimer
        ///
        ///[I] About
        ///---------------------------------------------------------------
        ///DeheadEmAll or DHEA is the original software application for automating the process of deheadering RO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeheadEmAll_HELP {
            get {
                return ResourceManager.GetString("DeheadEmAll_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------
        ///DeheadEmAll - Help - CMD version 20220308
        ///Copyright (c) 2016-2022 DeheadEmAll - All Rights Reserved
        ///------------------------------------------------------------------
        ///
        ///Usage:
        ///	DeheadEmAll-CLI.exe [-command] [option:]
        ///	Options that contain spaces must be enclosed in quotations
        ///	Options may be specified in any order
        ///	Only one command may be be used
        ///	If no command is passed then -deheadall will be used
        ///
        ///----------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeheadEmAll_HELP_CMD {
            get {
                return ResourceManager.GetString("DeheadEmAll_HELP_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------------------------------
        ///DeheadEmAll - License version 20220308
        ///Copyright (c) 2016-2022 DeheadEmAll - All Rights Reserved
        ///---------------------------------------------------------------
        ///
        ///TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///1. Redistributions in any form are not permitted whatsoever,
        ///    under any conditions.
        ///
        ///2. This software may not be reverse engineered, decompiled,
        ///    or disassembled.
        ///
        ///3. DeheadEmAll may publish revised and/or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeheadEmAll_LICENSE {
            get {
                return ResourceManager.GetString("DeheadEmAll_LICENSE", resourceCulture);
            }
        }
    }
}
